//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVGDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamesFor
    {
        public int ID { get; set; }
        public int GameID { get; set; }
        public int ConsoleID { get; set; }
    
        public virtual Console Console { get; set; }
        public virtual VideoGame VideoGame { get; set; }
    }
}
