//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVGDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoGame
    {
        public VideoGame()
        {
            this.GamesFors = new HashSet<GamesFor>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public int GameID { get; set; }
        public string Title { get; set; }
        public string Publisher { get; set; }
        public string Developer { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Console { get; set; }
        public string BoxArtLink { get; set; }
        public string Synopsis { get; set; }
    
        public virtual ICollection<GamesFor> GamesFors { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
